site_name: Setup Guides
site_url: https://lokeshnanda.github.io/setup-guides/
repo_url: https://github.com/LokeshNanda/setup-guides
docs_dir: docs

theme:
  name: material
  palette:
    primary: teal
plugins:
  - search

nav:
  - Home: index.md
  - Utils:
      - Github SSH for Multiple Client or Personal Projects: UTILS/github-multi-project-ssh-setup.md
      - Replace Obsidian Sync with Syncthing: UTILS/syncthing-obsidian-setup.md
      - Aiven DB Keep-Alive: UTILS/cloud-database-ping-daily.md

